In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('Mobile_phone_price.csv')
df

,Brand,Model,Storage,RAM,Screen Size (inches),Camera (MP),Battery Capacity (mAh),Price ($)
0,Apple,iPhone 13 Pro,128 GB,6 GB,6.1,12 + 12 + 12,3095,999
1,Samsung,Galaxy S21 Ultra,256 GB,12 GB,6.8,108 + 10 + 10 + 12,5000,1199
2,OnePlus,9 Pro,128 GB,8 GB,6.7,48 + 50 + 8 + 2,4500,899
3,Xiaomi,Redmi Note 10 Pro,128 GB,6 GB,6.67,64 + 8 + 5 + 2,5020,279
4,Google,Pixel 6,128 GB,8 GB,6.4,50 + 12.2,4614,799
...,...,...,...,...,...,...,...,...
402,Samsung,Galaxy Note20 5G,128,8,6.7,12+64+12,4300,1049
403,Xiaomi,Mi 10 Lite 5G,128,6,6.57,48+8+2+2,4160,349
404,Apple,iPhone 12 Pro Max,128,6,6.7,12+12+12,3687,1099
405,Oppo,Reno3,128,8,6.4,48+13+8+2,4025,429
406,Samsung,Galaxy S10 Lite,128,6,6.7,48+12+5,4500,649

In [3]:
df.sample(10)

,Brand,Model,Storage,RAM,Screen Size (inches),Camera (MP),Battery Capacity (mAh),Price ($)
317,Nokia,5.4,64,4,6.39,48+5+2+2,4000,179
262,Nokia,1.4,32GB,2GB,6.51,8MP + 2MP,4000,$119
83,Vivo,X70 Pro+,256GB,12GB,6.78,50MP + 48MP + 12MP + 8MP,4450,$999
277,Oppo,A12,64GB,4GB,6.22,13MP + 2MP,4230,$139
265,Oppo,A15s,64GB,4GB,6.52,13MP + 2MP + 2MP,4230,$159
167,Samsung,Galaxy M52 5G,128GB,6GB,6.7,64MP + 12MP + 5MP + 5MP,5000,$449
64,Realme,7i,128 GB,8 GB,6.5,64 + 8 + 2 + 2,5000,239
289,Apple,iPhone SE (2020),64,3,4.7,12,1821,399
281,Xiaomi,Redmi Note 7,64GB,4GB,6.3,48MP + 5MP,4000,$159
190,Vivo,V21 5G,128GB,8GB,6.44,64MP + 8MP + 2MP,4000,$399

In [4]:
df.shape #atribut dari dataframe df

(407, 8)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 407 entries, 0 to 406
Data columns (total 8 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Brand                   407 non-null    object
 1   Model                   407 non-null    object
 2   Storage                 407 non-null    object
 3   RAM                     407 non-null    object
 4   Screen Size (inches)    407 non-null    object
 5   Camera (MP)             407 non-null    object
 6   Battery Capacity (mAh)  407 non-null    int64
 7   Price ($)               407 non-null    object
dtypes: int64(1), object(7)
memory usage: 25.6+ KB

In [6]:
df.describe() #Statistik dasar

       Battery Capacity (mAh)
count              407.000000
mean              4676.476658
std                797.193713
min               1821.000000
25%               4300.000000
50%               5000.000000
75%               5000.000000
max               7000.000000

In [7]:
df['RAM '].unique()

array(['6 GB', '12 GB', '8 GB', '4 GB', '3 GB', '2 GB', '4GB', '8GB',
       '6GB', '12GB', '3GB', '2GB', '5GB', '12', '3', '6', '8', '4', '16',
       '2'], dtype=object)

In [8]:
df.columns

Index(['Brand', 'Model', 'Storage ', 'RAM ', 'Screen Size (inches)',
       'Camera (MP)', 'Battery Capacity (mAh)', 'Price ($)'],
      dtype='object')

In [9]:
df.nunique()

Brand                      16
Model                     239
Storage                    13
RAM                        20
Screen Size (inches)       41
Camera (MP)               143
Battery Capacity (mAh)     48
Price ($)                  89
dtype: int64

In [10]:
df['Price ($)'].unique()

array(['999', '1199', '899', '279', '799', '249', '699', '329', '449',
       '199', '299', '379', '179', '729', '599', '139', '189', '399',
       '259', '159', '229', '499', '129', '529', '369', '1099', '169',
       '99', '459', '239', '1299', '429', '659', '269', '359', '$799 ',
       '$399 ', '$699 ', '$329 ', '$999 ', '$549 ', '$1,299 ', '$899 ',
       '$449 ', '$319 ', '$269 ', '$349 ', '$279 ', '$249 ', '$299 ',
       '$969 ', '$1,199 ', '$149 ', '$139 ', '$99 ', '$199 ', '$169 ',
       '$499 ', '$179 ', '$219 ', '$229 ', '$239 ', '$109 ', '$189 ',
       '$389 ', '$309 ', '$369 ', '$129 ', '$849 ', '$469 ', '$209 ',
       '$119 ', '$339 ', '$429 ', '$159 ', '$379 ', '$289 ', '130', '749',
       '149', '969', '649', '349', '419', '1399', '1999', '119', '319',
       '1049'], dtype=object)

In [11]:
df['Screen Size (inches)'].unique()

array(['6.1', '6.8', '6.7', '6.67', '6.4', '6.55', '6.78', '6.43', '6.5',
       '6.62', '5.4', '6.2', '6.51', '6.6', '4.7', '6.58', '6.52', '6.44',
       '6.53', '6.56', '6.8 + 3.9', '4.5', '6.39', '5.9', '5.5', '6.81',
       '5.99', '6.82', '6.3', '6.22', '6', '6.35', '6.9', '6.76', '6.49',
       '6.72', '5.7', '6.47', '7.6 (unfolded)', '6.15', '6.57'],
      dtype=object)

In [12]:
df[df['Screen Size (inches)'] == '7.6 (unfolded)']

,Brand,Model,Storage,RAM,Screen Size (inches),Camera (MP),Battery Capacity (mAh),Price ($)
373,Samsung,Galaxy Z Fold2 5G,256,12,7.6 (unfolded),12+12+12,4500,1999

In [13]:
#cleansing data
df['Price ($)'] = df['Price ($)'].str.replace('$','')
df['Price ($)'] = df['Price ($)'].str.replace(',','')
df['Price ($)'] = df['Price ($)'].astype(int)
df.describe()

<ipython-input-13-3c5b05fc9d38>:2: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  df['Price ($)'] = df['Price ($)'].str.replace('$','')

       Battery Capacity (mAh)    Price ($)
count              407.000000   407.000000
mean              4676.476658   408.314496
std                797.193713   299.684768
min               1821.000000    99.000000
25%               4300.000000   199.000000
50%               5000.000000   299.000000
75%               5000.000000   499.000000
max               7000.000000  1999.000000

In [14]:
df['Price ($)'].unique()

array([ 999, 1199,  899,  279,  799,  249,  699,  329,  449,  199,  299,
        379,  179,  729,  599,  139,  189,  399,  259,  159,  229,  499,
        129,  529,  369, 1099,  169,   99,  459,  239, 1299,  429,  659,
        269,  359,  549,  319,  349,  969,  149,  219,  109,  389,  309,
        849,  469,  209,  119,  339,  289,  130,  749,  649,  419, 1399,
       1999, 1049])

In [15]:
import re
harga = '$1,299 '
harga = re.sub('\D', '', harga) # menghapus semua kemungkinan selain angka
harga

'1299'

In [16]:
df['RAM '] = df['RAM '].str.replace('GB', '')
df['RAM '] = df['RAM '].str.replace(' ', '')
df['RAM '] = df['RAM '].astype(int)

In [17]:
df.describe()

             RAM   Battery Capacity (mAh)    Price ($)
count  407.000000              407.000000   407.000000
mean     5.837838             4676.476658   408.314496
std      2.431980              797.193713   299.684768
min      2.000000             1821.000000    99.000000
25%      4.000000             4300.000000   199.000000
50%      6.000000             5000.000000   299.000000
75%      8.000000             5000.000000   499.000000
max     16.000000             7000.000000  1999.000000

In [18]:
df.sort_values(by = ['Battery Capacity (mAh)'])

,Brand,Model,Storage,RAM,Screen Size (inches),Camera (MP),Battery Capacity (mAh),Price ($)
289,Apple,iPhone SE (2020),64,3,4.7,12,1821,399
32,Apple,iPhone SE (2nd Gen),64 GB,3,4.7,12,1821,399
379,Apple,iPhone SE (2020),128,3,4.7,12,1821,449
333,Apple,iPhone SE (2020),64,3,4.7,12,1821,399
62,Apple,iPhone SE (2020),64 GB,3,4.7,12,1821,399
...,...,...,...,...,...,...,...,...
286,Xiaomi,Redmi 9T,128GB,4,6.53,48MP + 8MP + 2MP + 2MP,6000,229
175,Realme,C25s,128GB,4,6.5,13MP + 2MP + 2MP,6000,149
236,Samsung,Galaxy M12,64GB,4,6.5,48MP + 5MP + 2MP + 2MP,6000,179
208,Samsung,Galaxy M62,128GB,8,6.7,64MP + 12MP + 5MP + 5MP,7000,429
334,Samsung,Galaxy M51,128,6,6.7,64+12+5+5,7000,449

In [19]:
df.sort_values(by = ['Battery Capacity (mAh)', 'Price ($)'], ascending = [True,False])

,Brand,Model,Storage,RAM,Screen Size (inches),Camera (MP),Battery Capacity (mAh),Price ($)
379,Apple,iPhone SE (2020),128,3,4.7,12,1821,449
32,Apple,iPhone SE (2nd Gen),64 GB,3,4.7,12,1821,399
62,Apple,iPhone SE (2020),64 GB,3,4.7,12,1821,399
289,Apple,iPhone SE (2020),64,3,4.7,12,1821,399
333,Apple,iPhone SE (2020),64,3,4.7,12,1821,399
...,...,...,...,...,...,...,...,...
198,Motorola,Moto G9 Power Lite,64GB,4,6.5,48MP + 2MP + 2MP,6000,149
217,Nokia,C30,32GB,2,6.82,13MP + 2MP,6000,149
397,Xiaomi,Poco M3,128,4,6.53,48+2+2,6000,149
334,Samsung,Galaxy M51,128,6,6.7,64+12+5+5,7000,449
208,Samsung,Galaxy M62,128GB,8,6.7,64MP + 12MP + 5MP + 5MP,7000,429

In [20]:
df[(df['Brand'] == 'Xiaomi') & (df['RAM '] == 6)]

,Brand,Model,Storage,RAM,Screen Size (inches),Camera (MP),Battery Capacity (mAh),Price ($)
3,Xiaomi,Redmi Note 10 Pro,128 GB,6,6.67,64 + 8 + 5 + 2,5020,279
7,Xiaomi,Poco X3 Pro,128 GB,6,6.67,48 + 8 + 2 + 2,5160,249
15,Xiaomi,Mi 11 Lite 5G NE,128 GB,6,6.55,64 + 8 + 5,4250,329
20,Xiaomi,Redmi 10 Prime,128 GB,6,6.5,50 + 8 + 2 + 2,6000,179
24,Xiaomi,Redmi Note 10 Pro Max,128 GB,6,6.67,108 + 8 + 5 + 2,5020,279
67,Xiaomi,Redmi Note 10S,128 GB,6,6.43,64 + 8 + 2 + 2,5000,229
73,Xiaomi,Mi 11 Lite 5G,128 GB,6,6.55,64 + 8 + 5,4250,369
81,Xiaomi,Poco X4 Pro,128GB,6,6.67,48MP + 8MP + 2MP + 2MP,5160,329
92,Xiaomi,Redmi Note 10 Pro Max,128GB,6,6.67,108MP + 8MP + 5MP + 2MP,5020,319
110,Xiaomi,Poco M3 Pro 5G,128GB,6,6.5,48MP + 2MP + 2MP,5000,199
117,Xiaomi,Redmi 10 Prime,128GB,6,6.5,50MP + 8MP + 2MP + 2MP,6000,219
126,Xiaomi,Mi 11 Lite 5G,128GB,6,6.55,64MP + 8MP + 5MP,4250,399
164,Xiaomi,Redmi Note 10S,128GB,6,6.43,64MP + 8MP + 2MP + 2MP,5000,229
169,Xiaomi,Redmi Note 9 Pro Max,128GB,6,6.67,64MP + 8MP + 5MP + 2MP,5020,279
174,Xiaomi,Poco X3 Pro,128GB,6,6.67,48MP + 8MP + 2MP + 2MP,5160,249
182,Xiaomi,Mi 11 Lite NE,128GB,6,6.55,64MP + 8MP + 5MP,4250,329
186,Xiaomi,Redmi Note 10 Pro,128GB,6,6.67,64MP + 8MP + 5MP + 2MP,5020,329
193,Xiaomi,Redmi 9 Activ,128GB,6,6.53,50MP + 2MP,5000,209
201,Xiaomi,Redmi Note 10S,128GB,6,6.43,64MP + 8MP + 2MP + 2MP,5000,279
206,Xiaomi,Mi 10i,128GB,6,6.67,108MP + 8MP + 2MP + 2MP,4820,319
210,Xiaomi,Redmi 10 Prime,128GB,6,6.5,50MP + 8MP + 2MP + 2MP,6000,199
213,Xiaomi,Poco X3 Pro,128GB,6,6.67,48MP + 8MP + 2MP + 2MP,5160,299
246,Xiaomi,Poco X3 Pro,128GB,6,6.67,48MP + 8MP + 2MP + 2MP,5160,249
257,Xiaomi,Redmi Note 9 Pro Max,64GB,6,6.67,64MP + 8MP + 5MP + 2MP,5020,279
290,Xiaomi,Poco X3 Pro,128,6,6.67,48+8+2+2,5160,249
310,Xiaomi,Redmi Note 10 Pro,128,6,6.67,108+8+5+2,5020,279
331,Xiaomi,Poco X3 Pro,128,6,6.67,48+8+2+2,5160,249
340,Xiaomi,Redmi Note 9S,128,6,6.67,48+8+5+2,5020,249
346,Xiaomi,Mi 10T Lite,128,6,6.67,64+8+2+2,4820,279
352,Xiaomi,Mi 11 Lite,128,6,6.55,64+8+5,4250,399
368,Xiaomi,Redmi Note 9S,128,6,6.67,48+8+5+2,5020,229
386,Xiaomi,Redmi Note 10 Pro,128,6,6.67,108+8+5+2,5020,329
403,Xiaomi,Mi 10 Lite 5G,128,6,6.57,48+8+2+2,4160,349

In [21]:
df.loc[(df['Brand'] == 'Xiaomi'), ['Brand', 'Model', 'Price ($)']]

      Brand                  Model  Price ($)
3    Xiaomi      Redmi Note 10 Pro        279
7    Xiaomi            Poco X3 Pro        249
15   Xiaomi       Mi 11 Lite 5G NE        329
20   Xiaomi         Redmi 10 Prime        179
24   Xiaomi  Redmi Note 10 Pro Max        279
..      ...                    ...        ...
380  Xiaomi               Redmi 9C        119
386  Xiaomi      Redmi Note 10 Pro        329
389  Xiaomi               Redmi 9T        199
397  Xiaomi                Poco M3        149
403  Xiaomi          Mi 10 Lite 5G        349

[67 rows x 3 columns]

In [22]:
df.iloc[0:5, 1:3] #ambil baris & kolom

               Model Storage
0      iPhone 13 Pro   128 GB
1   Galaxy S21 Ultra   256 GB
2              9 Pro   128 GB
3  Redmi Note 10 Pro   128 GB
4            Pixel 6   128 GB

In [23]:
df['battery dollar'] = df['Battery Capacity (mAh)'] / df['Price ($)']
df
#semakin tinggi nilai battery dollar, berarti semakin besar kapasitasnya tetapi harganya murah

,Brand,Model,Storage,RAM,Screen Size (inches),Camera (MP),Battery Capacity (mAh),Price ($),battery dollar
0,Apple,iPhone 13 Pro,128 GB,6,6.1,12 + 12 + 12,3095,999,3.098098
1,Samsung,Galaxy S21 Ultra,256 GB,12,6.8,108 + 10 + 10 + 12,5000,1199,4.170142
2,OnePlus,9 Pro,128 GB,8,6.7,48 + 50 + 8 + 2,4500,899,5.005562
3,Xiaomi,Redmi Note 10 Pro,128 GB,6,6.67,64 + 8 + 5 + 2,5020,279,17.992832
4,Google,Pixel 6,128 GB,8,6.4,50 + 12.2,4614,799,5.774718
...,...,...,...,...,...,...,...,...,...
402,Samsung,Galaxy Note20 5G,128,8,6.7,12+64+12,4300,1049,4.099142
403,Xiaomi,Mi 10 Lite 5G,128,6,6.57,48+8+2+2,4160,349,11.919771
404,Apple,iPhone 12 Pro Max,128,6,6.7,12+12+12,3687,1099,3.354868
405,Oppo,Reno3,128,8,6.4,48+13+8+2,4025,429,9.382284
406,Samsung,Galaxy S10 Lite,128,6,6.7,48+12+5,4500,649,6.933744

In [24]:
df.sort_values(by=['battery dollar'], ascending = False)

,Brand,Model,Storage,RAM,Screen Size (inches),Camera (MP),Battery Capacity (mAh),Price ($),battery dollar
273,Realme,C11,32GB,2,6.5,13MP + 2MP,5000,99,50.505051
216,Realme,C11 2021,32GB,2,6.52,8MP + 2MP,5000,99,50.505051
53,Realme,Narzo 50i,32 GB,2,6.5,50 + 2,5000,99,50.505051
109,Motorola,Moto E7i Power,32GB,2,6.5,13MP + 2MP,5000,99,50.505051
250,Realme,C11 2021,32GB,2,6.5,8MP + 2MP,5000,99,50.505051
...,...,...,...,...,...,...,...,...,...
361,Huawei,P40 Pro+,512,8,6.58,50+40+12+3D,4200,1399,3.002144
338,Apple,iPhone XS Max,256,4,6.5,12+12,3174,1099,2.888080
384,Apple,iPhone 12 Pro,128,6,6.1,12+12+12,2815,999,2.817818
369,Apple,iPhone 12 mini,256,4,5.4,12+12,2227,899,2.477197
373,Samsung,Galaxy Z Fold2 5G,256,12,7.6 (unfolded),12+12+12,4500,1999,2.251126

In [25]:
df.groupby('Brand').agg(ratarata_harga = ('Price ($)', 'mean'), avg_battery_cap = ('Battery Capacity (mAh)','mean'))

            ratarata_harga  avg_battery_cap
Brand
Apple           745.666667      2863.900000
Asus            874.000000      5000.000000
Blackberry      499.000000      3500.000000
CAT             299.000000      4200.000000
Google          699.000000      4019.857143
Huawei          783.166667      4161.666667
LG              615.666667      4100.000000
Motorola        278.130435      5021.739130
Nokia           244.714286      4502.857143
OnePlus         644.333333      4415.000000
Oppo            376.142857      4631.339286
Realme          206.906977      5176.744186
Samsung         480.405063      4936.708861
Sony           1299.000000      4500.000000
Vivo            323.000000      4750.000000
Xiaomi          282.880597      5101.791045

In [26]:
pd.crosstab(df['Brand'], df['RAM '])

RAM         2   3   4   5   6   8   12  16
Brand
Apple        0  11  14   0   5   0   0   0
Asus         0   0   0   0   1   3   0   0
Blackberry   0   0   1   0   2   0   0   0
CAT          0   1   0   0   0   0   0   0
Google       0   0   0   0   2   5   0   0
Huawei       0   0   2   0   0  10   0   0
LG           0   0   0   0   2   1   0   0
Motorola     1   2  14   2   3   0   1   0
Nokia        4   8  10   0   4   2   0   0
OnePlus      0   0   0   0   3   8   4   0
Oppo         0   4  13   0  14  15  10   0
Realme       5   2  20   0   5  11   0   0
Samsung      1   4  26   0  29  12   6   1
Sony         0   0   0   0   0   1   0   0
Vivo         0   5   5   0   4  18   3   0
Xiaomi       0   1  23   0  33   9   1   0

In [27]:
df.pivot_table(index = ['Brand'], values = ['Price ($)','RAM '], aggfunc=['mean','max','std'])

                   mean                 max              std
              Price ($)      RAM  Price ($) RAM    Price ($)      RAM
Brand
Apple        745.666667  3.966667      1299    6  258.621456  1.033352
Asus         874.000000  7.500000       999    8  125.830574  1.000000
Blackberry   499.000000  5.333333       699    6  173.205081  1.154701
CAT          299.000000  3.000000       299    3         NaN       NaN
Google       699.000000  7.428571       799    8  100.000000  0.975900
Huawei       783.166667  7.333333      1399    8  404.665032  1.556998
LG           615.666667  6.666667       999    8  340.342964  1.154701
Motorola     278.130435  4.521739       699   12  127.632749  1.879786
Nokia        244.714286  4.000000       549    8  140.513043  1.632993
OnePlus      644.333333  8.666667       999   12  258.729497  2.225395
Oppo         376.142857  6.928571      1199   12  235.462518  2.891097
Realme       206.906977  4.976744       399    8   85.761523  2.052738
Samsung      480.405063  6.025316      1999   16  367.849695  2.581863
Sony        1299.000000  8.000000      1299    8         NaN       NaN
Vivo         323.000000  6.828571      1199   12  233.215376  2.549345
Xiaomi       282.880597  5.626866      1199   12  161.329281  1.574761

In [28]:
df.pivot_table(index = 'Brand', values = 'Price ($)', columns = 'RAM ', aggfunc = 'mean')

RAM,2,3,4,5,6,8,12,16
Brand,,,,,,,,
Apple,NaN,494.454545,838.285714,NaN,1039.000000,NaN,NaN,NaN
Asus,NaN,NaN,NaN,NaN,699.000000,932.333333,NaN,NaN
Blackberry,NaN,NaN,399.000000,NaN,549.000000,NaN,NaN,NaN
CAT,NaN,299.000000,NaN,NaN,NaN,NaN,NaN,NaN
Google,NaN,NaN,NaN,NaN,649.000000,719.000000,NaN,NaN
Huawei,NaN,NaN,264.000000,NaN,NaN,887.000000,NaN,NaN
LG,NaN,NaN,NaN,NaN,424.000000,999.000000,NaN,NaN
Motorola,99.0,184.000000,239.714286,399.0,359.000000,NaN,699.0,NaN
Nokia,134.0,142.750000,228.000000,NaN,474.000000,499.000000,NaN,NaN
OnePlus,NaN,NaN,NaN,NaN,309.000000,631.500000,921.5,NaN
Oppo,NaN,151.500000,190.538462,NaN,272.571429,407.666667,805.0,NaN
Realme,99.0,129.000000,166.500000,NaN,291.000000,305.363636,NaN,NaN
Samsung,129.0,139.250000,231.692308,NaN,441.068966,746.500000,1349.0,1399.0
Sony,NaN,NaN,NaN,NaN,NaN,1299.000000,NaN,NaN
Vivo,NaN,145.000000,179.000000,NaN,219.000000,322.888889,999.0,NaN
Xiaomi,NaN,119.000000,182.913043,NaN,279.909091,465.666667,1199.0,NaN

In [29]:
df_melt = df.melt(id_vars = ['Brand', 'Model', 'RAM ', 'Storage ', 'Screen Size (inches)', 'Camera (MP)'], \
var_name = 'nama_kolom', value_name = 'nilai')
df_melt

,Brand,Model,RAM,Storage,Screen Size (inches),Camera (MP),nama_kolom,nilai
0,Apple,iPhone 13 Pro,6,128 GB,6.1,12 + 12 + 12,Battery Capacity (mAh),3095.000000
1,Samsung,Galaxy S21 Ultra,12,256 GB,6.8,108 + 10 + 10 + 12,Battery Capacity (mAh),5000.000000
2,OnePlus,9 Pro,8,128 GB,6.7,48 + 50 + 8 + 2,Battery Capacity (mAh),4500.000000
3,Xiaomi,Redmi Note 10 Pro,6,128 GB,6.67,64 + 8 + 5 + 2,Battery Capacity (mAh),5020.000000
4,Google,Pixel 6,8,128 GB,6.4,50 + 12.2,Battery Capacity (mAh),4614.000000
...,...,...,...,...,...,...,...,...
1216,Samsung,Galaxy Note20 5G,8,128,6.7,12+64+12,battery dollar,4.099142
1217,Xiaomi,Mi 10 Lite 5G,6,128,6.57,48+8+2+2,battery dollar,11.919771
1218,Apple,iPhone 12 Pro Max,6,128,6.7,12+12+12,battery dollar,3.354868
1219,Oppo,Reno3,8,128,6.4,48+13+8+2,battery dollar,9.382284
1220,Samsung,Galaxy S10 Lite,6,128,6.7,48+12+5,battery dollar,6.933744

In [30]:
df_melt.sort_values(by = ['Brand']).head(20)

,Brand,Model,RAM,Storage,Screen Size (inches),Camera (MP),nama_kolom,nilai
0,Apple,iPhone 13 Pro,6,128 GB,6.1,12 + 12 + 12,Battery Capacity (mAh),3095.000000
469,Apple,iPhone SE (2020),3,64 GB,4.7,12,Price ($),399.000000
475,Apple,iPhone XR,3,64 GB,6.1,12 + 12,Price ($),499.000000
481,Apple,iPhone 11,4,128 GB,6.1,12 + 12,Price ($),599.000000
484,Apple,iPhone 13,4,128GB,6.1,12MP + 12MP,Price ($),799.000000
1147,Apple,iPhone SE (2020),3,64,4.7,12,battery dollar,4.563910
1152,Apple,iPhone XS Max,4,256,6.5,12+12,battery dollar,2.888080
1161,Apple,iPhone 8 Plus,3,64,5.5,12+12,battery dollar,3.849785
891,Apple,iPhone 13,4,128GB,6.1,12MP + 12MP,battery dollar,3.523154
888,Apple,iPhone 11,4,128 GB,6.1,12 + 12,battery dollar,5.191987
882,Apple,iPhone XR,3,64 GB,6.1,12 + 12,battery dollar,5.895792
1169,Apple,iPhone XR,3,64,6.1,12,battery dollar,5.895792
876,Apple,iPhone SE (2020),3,64 GB,4.7,12,battery dollar,4.563910
1140,Apple,iPhone 11,4,64,6.1,12+12+12,battery dollar,4.449213
871,Apple,iPhone 13 Pro Max,6,256 GB,6.7,12 + 12 + 12,battery dollar,3.350269
859,Apple,iPhone 12 Mini,4,64 GB,5.4,12 + 12,battery dollar,3.185980
77,Apple,iPhone 13,4,128GB,6.1,12MP + 12MP,Battery Capacity (mAh),2815.000000
853,Apple,iPhone XR,3,64 GB,6.1,12,battery dollar,5.895792
74,Apple,iPhone 11,4,128 GB,6.1,12 + 12,Battery Capacity (mAh),3110.000000
1176,Apple,iPhone 11 Pro Max,4,64,6.5,12+12+12,battery dollar,3.611465

In [31]:
df.stack().head(30)

0  Brand                                  Apple
   Model                          iPhone 13 Pro
   Storage                               128 GB
   RAM                                        6
   Screen Size (inches)                     6.1
   Camera (MP)                     12 + 12 + 12
   Battery Capacity (mAh)                  3095
   Price ($)                                999
   battery dollar                      3.098098
1  Brand                                Samsung
   Model                       Galaxy S21 Ultra
   Storage                               256 GB
   RAM                                       12
   Screen Size (inches)                     6.8
   Camera (MP)               108 + 10 + 10 + 12
   Battery Capacity (mAh)                  5000
   Price ($)                               1199
   battery dollar                      4.170142
2  Brand                                OnePlus
   Model                                  9 Pro
   Storage                               128 GB
   RAM                                        8
   Screen Size (inches)                     6.7
   Camera (MP)                  48 + 50 + 8 + 2
   Battery Capacity (mAh)                  4500
   Price ($)                                899
   battery dollar                      5.005562
3  Brand                                 Xiaomi
   Model                      Redmi Note 10 Pro
   Storage                               128 GB
dtype: object

In [32]:
df = df.rename(columns = {'Storage ':'Storage', 'RAM ':'RAM'})

In [33]:
df.columns

Index(['Brand', 'Model', 'Storage', 'RAM', 'Screen Size (inches)',
       'Camera (MP)', 'Battery Capacity (mAh)', 'Price ($)', 'battery dollar'],
      dtype='object')

In [34]:
# mengkategorisasikan nilai Price menjadi 4 kategori dengan jumlah ukuran yang sama, misal Bronze, Silver, Gold, Platinum
bin_labels = ['Bronze', 'Silver', 'Gold', 'Platinum']
results, bin_edges = pd.qcut(df['Price ($)'], q = 4, labels = bin_labels,retbins = True)
results.value_counts()

Bronze      119
Silver      101
Platinum     95
Gold         92
Name: Price ($), dtype: int64

In [35]:
bin_edges

array([  99.,  199.,  299.,  499., 1999.])

In [36]:
results_table = pd.DataFrame(zip(bin_edges, bin_labels), columns =['Threshold','Tier'])
results_table

   Threshold      Tier
0       99.0    Bronze
1      199.0    Silver
2      299.0      Gold
3      499.0  Platinum

In [37]:
df['results'] = results
df

,Brand,Model,Storage,RAM,Screen Size (inches),Camera (MP),Battery Capacity (mAh),Price ($),battery dollar,results
0,Apple,iPhone 13 Pro,128 GB,6,6.1,12 + 12 + 12,3095,999,3.098098,Platinum
1,Samsung,Galaxy S21 Ultra,256 GB,12,6.8,108 + 10 + 10 + 12,5000,1199,4.170142,Platinum
2,OnePlus,9 Pro,128 GB,8,6.7,48 + 50 + 8 + 2,4500,899,5.005562,Platinum
3,Xiaomi,Redmi Note 10 Pro,128 GB,6,6.67,64 + 8 + 5 + 2,5020,279,17.992832,Silver
4,Google,Pixel 6,128 GB,8,6.4,50 + 12.2,4614,799,5.774718,Platinum
...,...,...,...,...,...,...,...,...,...,...
402,Samsung,Galaxy Note20 5G,128,8,6.7,12+64+12,4300,1049,4.099142,Platinum
403,Xiaomi,Mi 10 Lite 5G,128,6,6.57,48+8+2+2,4160,349,11.919771,Gold
404,Apple,iPhone 12 Pro Max,128,6,6.7,12+12+12,3687,1099,3.354868,Platinum
405,Oppo,Reno3,128,8,6.4,48+13+8+2,4025,429,9.382284,Gold
406,Samsung,Galaxy S10 Lite,128,6,6.7,48+12+5,4500,649,6.933744,Platinum

In [38]:
df['results'].value_counts()

Bronze      119
Silver      101
Platinum     95
Gold         92
Name: results, dtype: int64

In [39]:
bins = [0, 1000, 2000, 3000, 4000, 5000, 10000]
labels = [1, 2, 3, 4, 5, 6]
df['binned_battery'] = pd.cut(df['Battery Capacity (mAh)'], bins = bins, labels = labels)

In [40]:
df

,Brand,Model,Storage,RAM,Screen Size (inches),Camera (MP),Battery Capacity (mAh),Price ($),battery dollar,results,binned_battery
0,Apple,iPhone 13 Pro,128 GB,6,6.1,12 + 12 + 12,3095,999,3.098098,Platinum,4
1,Samsung,Galaxy S21 Ultra,256 GB,12,6.8,108 + 10 + 10 + 12,5000,1199,4.170142,Platinum,5
2,OnePlus,9 Pro,128 GB,8,6.7,48 + 50 + 8 + 2,4500,899,5.005562,Platinum,5
3,Xiaomi,Redmi Note 10 Pro,128 GB,6,6.67,64 + 8 + 5 + 2,5020,279,17.992832,Silver,6
4,Google,Pixel 6,128 GB,8,6.4,50 + 12.2,4614,799,5.774718,Platinum,5
...,...,...,...,...,...,...,...,...,...,...,...
402,Samsung,Galaxy Note20 5G,128,8,6.7,12+64+12,4300,1049,4.099142,Platinum,5
403,Xiaomi,Mi 10 Lite 5G,128,6,6.57,48+8+2+2,4160,349,11.919771,Gold,5
404,Apple,iPhone 12 Pro Max,128,6,6.7,12+12+12,3687,1099,3.354868,Platinum,4
405,Oppo,Reno3,128,8,6.4,48+13+8+2,4025,429,9.382284,Gold,5
406,Samsung,Galaxy S10 Lite,128,6,6.7,48+12+5,4500,649,6.933744,Platinum,5

In [41]:
df['binned_battery'].value_counts()

5    268
6     66
4     52
3     16
2      5
1      0
Name: binned_battery, dtype: int64

In [42]:
df['rank_price'] = df['Price ($)'].rank(ascending = True, method = 'first')
df

,Brand,Model,Storage,RAM,Screen Size (inches),Camera (MP),Battery Capacity (mAh),Price ($),battery dollar,results,binned_battery,rank_price
0,Apple,iPhone 13 Pro,128 GB,6,6.1,12 + 12 + 12,3095,999,3.098098,Platinum,4,374.0
1,Samsung,Galaxy S21 Ultra,256 GB,12,6.8,108 + 10 + 10 + 12,5000,1199,4.170142,Platinum,5,394.0
2,OnePlus,9 Pro,128 GB,8,6.7,48 + 50 + 8 + 2,4500,899,5.005562,Platinum,5,367.0
3,Xiaomi,Redmi Note 10 Pro,128 GB,6,6.67,64 + 8 + 5 + 2,5020,279,17.992832,Silver,6,174.0
4,Google,Pixel 6,128 GB,8,6.4,50 + 12.2,4614,799,5.774718,Platinum,5,352.0
...,...,...,...,...,...,...,...,...,...,...,...,...
402,Samsung,Galaxy Note20 5G,128,8,6.7,12+64+12,4300,1049,4.099142,Platinum,5,386.0
403,Xiaomi,Mi 10 Lite 5G,128,6,6.57,48+8+2+2,4160,349,11.919771,Gold,5,250.0
404,Apple,iPhone 12 Pro Max,128,6,6.7,12+12+12,3687,1099,3.354868,Platinum,4,393.0
405,Oppo,Reno3,128,8,6.4,48+13+8+2,4025,429,9.382284,Gold,5,284.0
406,Samsung,Galaxy S10 Lite,128,6,6.7,48+12+5,4500,649,6.933744,Platinum,5,325.0

In [43]:
df.sort_values(by = ['rank_price'])

,Brand,Model,Storage,RAM,Screen Size (inches),Camera (MP),Battery Capacity (mAh),Price ($),battery dollar,results,binned_battery,rank_price
53,Realme,Narzo 50i,32 GB,2,6.5,50 + 2,5000,99,50.505051,Bronze,5,1.0
107,Nokia,C20 Plus,32GB,3,6.5,8MP + 2MP,4950,99,50.000000,Bronze,5,2.0
109,Motorola,Moto E7i Power,32GB,2,6.5,13MP + 2MP,5000,99,50.505051,Bronze,5,3.0
216,Realme,C11 2021,32GB,2,6.52,8MP + 2MP,5000,99,50.505051,Bronze,5,4.0
240,Nokia,C20 Plus,32GB,3,6.5,8MP + 2MP,4950,99,50.000000,Bronze,5,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...
87,Sony,Xperia 5 III,128GB,8,6.1,12MP + 12MP + 12MP,4500,1299,3.464203,Platinum,5,403.0
288,Samsung,Galaxy Note 20 Ultra,256,12,6.9,108+12+12,4500,1299,3.464203,Platinum,5,404.0
361,Huawei,P40 Pro+,512,8,6.58,50+40+12+3D,4200,1399,3.002144,Platinum,5,405.0
367,Samsung,Galaxy S20 Ultra 5G,512,16,6.9,108+48+12+3D,5000,1399,3.573981,Platinum,5,406.0
373,Samsung,Galaxy Z Fold2 5G,256,12,7.6 (unfolded),12+12+12,4500,1999,2.251126,Platinum,5,407.0

In [44]:
df[df['rank_price'] == 4.5]

Empty DataFrame
Columns: [Brand, Model, Storage, RAM, Screen Size (inches), Camera (MP), Battery Capacity (mAh), Price ($), battery dollar, results, binned_battery, rank_price]
Index: []

In [45]:
body = ['Samsung', 'Xiaomi']
df[df['Brand'].isin(body)]

,Brand,Model,Storage,RAM,Screen Size (inches),Camera (MP),Battery Capacity (mAh),Price ($),battery dollar,results,binned_battery,rank_price
1,Samsung,Galaxy S21 Ultra,256 GB,12,6.8,108 + 10 + 10 + 12,5000,1199,4.170142,Platinum,5,394.0
3,Xiaomi,Redmi Note 10 Pro,128 GB,6,6.67,64 + 8 + 5 + 2,5020,279,17.992832,Silver,6,174.0
6,Samsung,Galaxy Z Flip3,256 GB,8,6.7,12 + 12,3300,999,3.303303,Platinum,4,375.0
7,Xiaomi,Poco X3 Pro,128 GB,6,6.67,48 + 8 + 2 + 2,5160,249,20.722892,Silver,6,146.0
11,Samsung,Galaxy A52s 5G,128 GB,6,6.5,64 + 12 + 5 + 5,4500,449,10.022272,Gold,5,285.0
...,...,...,...,...,...,...,...,...,...,...,...,...
397,Xiaomi,Poco M3,128,4,6.53,48+2+2,6000,149,40.268456,Bronze,6,48.0
398,Samsung,Galaxy A52 5G,128,6,6.5,64+12+5+5,4500,449,10.022272,Gold,5,300.0
402,Samsung,Galaxy Note20 5G,128,8,6.7,12+64+12,4300,1049,4.099142,Platinum,5,386.0
403,Xiaomi,Mi 10 Lite 5G,128,6,6.57,48+8+2+2,4160,349,11.919771,Gold,5,250.0
406,Samsung,Galaxy S10 Lite,128,6,6.7,48+12+5,4500,649,6.933744,Platinum,5,325.0